Repository a11yphant/a11yphant, pull requests merged in 2023-03, with the labels that each got.

#33 update submission checker dependencies
  services/submission-checker/package-lock.json
  services/submission-checker/package.json
Labels: Submission Checker

#37 Site Minor Dependency Updates
  services/site/package-lock.json
  services/site/package.json
Labels: Site, Maintenance

#31 Update: issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Documentation

#41 Add dependabot config
  .github/dependabot.yml
Labels: Infrastructure

#40 Add a bio to each team member
  README.md
  services/site/public/images/github-docs/johanna-wicht-2023.jpg
Labels: Documentation

#42 add replaces-base to dependabot config
  .github/dependabot.yml
Labels: Infrastructure

#47 Refactor: In-Text-Link Component to replace duplicate code
  services/site/src/components/links/InTextLink.tsx
  services/site/src/pages/about.tsx
  services/site/src/pages/index.tsx
  services/site/src/pages/legal-notice.tsx
  services/site/src/pages/press-kit.tsx
  services/site/src/pages/privacy-policy.tsx
  services/site/tests/components/links/InTextLink.spec.tsx
Labels: Site

#46 Element Contains Check
  challenges/rule-element-contains-text.yml
  challenges/rule-element-not-contains-text.yml
  services/submission-checker/src/app.module.ts
  services/submission-checker/src/check-to-class-map.ts
  services/submission-checker/src/checks/element-contains-text.check.ts
  services/submission-checker/src/checks/element-exists.check.ts
  services/submission-checker/src/checks/element-not-contains-text.check.ts
  services/submission-checker/src/checks/element-not-exists.check.ts
  services/submission-checker/tests/checks/element-contains-text.check.spec.ts
  services/submission-checker/tests/checks/element-not-contains-text.check.spec.ts
Labels: Submission Checker

#59 fix: wording in team bio to fit the others
  README.md
  services/site/src/pages/press-kit.tsx
Labels: Content
