Repository a11yphant/a11yphant, pull requests merged in 2024-09, with the labels that each got.

#227 Hotfix/SEO meta tags
  services/site/src/app/challenges/[challengeSlug]/page.tsx
  services/site/src/pages/challenges/[challengeSlug]/level/[nthLevel].tsx
Labels: Bug, Site, Content

#228 Hotfix/flash message after login
  services/site/src/components/common/flashMessage/FlashMessage.tsx
Labels: Bug, Site

#229 Refactor/opens in new tab
  README.md
  services/site/src/app/challenges/page.tsx
  services/site/src/components/Footer.tsx
  services/site/src/components/homepage/QuoteCard.tsx
  services/site/src/components/icons/NewTab.tsx
  services/site/src/pages/about.tsx
  services/site/src/pages/legal-notice.tsx
  services/site/src/pages/press-kit.tsx
  services/site/src/pages/privacy-policy.tsx
  services/site/tests/components/icons/Icons.spec.tsx
Labels: enhancement, Site

#230 refactor: replace allyphant with a11yphant
  README.md
  services/site/src/components/Navigation.tsx
  services/site/src/components/homepage/HeroSection.tsx
  services/site/src/components/homepage/SignUpSection.tsx
  services/site/src/pages/about.tsx
  services/site/src/pages/index.tsx
  services/site/src/pages/press-kit.tsx
  services/site/src/pages/privacy-policy.tsx
Labels: enhancement, Site

#234 Refactor/a11y improvements
  services/site/src/components/challenge/Editors.tsx
  services/site/src/components/challenge/Preview.tsx
  services/site/src/components/challenge/Sidebar.tsx
  services/site/src/components/challenge/level/QuizLevel.tsx
  services/site/src/components/homepage/MediaSection.tsx
  services/site/src/components/homepage/TestimonialSection.tsx
  services/site/src/components/homepage/TopChallengeSection.tsx
  services/site/src/pages/_error.tsx
  services/site/src/pages/about.tsx
  services/site/src/pages/press-kit.tsx
  services/site/src/pages/privacy-policy.tsx
  services/site/tests/components/challenge/Editors.spec.tsx
Labels: Bug, Site

#238 Refactor/twitter to x
  README.md
  src/app/challenges/page.tsx
  src/components/Footer.tsx
  src/components/challengePage/ChallengeHeader.tsx
  src/components/challengePage/ChallengeList.tsx
  src/components/challengePage/ChallengeSignUpPrompt.tsx
  src/components/common/flashMessage/FlashMessage.tsx
  src/components/evaluation/CollapsableSection.tsx
  src/components/icons/ClosingX.tsx
  src/components/icons/XTwitter.tsx
  src/components/modal/Modal.tsx
  src/components/user/LoginBox.tsx
  src/components/user/SignUpBox.tsx
  src/pages/about.tsx
  src/pages/index.tsx
  src/pages/press-kit.tsx
  src/pages/privacy-policy.tsx
  src/pages/profile/[userId].tsx
  tests/components/challengePage/ChallengeHeader.spec.tsx
  tests/components/challengePage/ChallengeSignUpPrompt.spec.tsx
  tests/components/icons/Icons.spec.tsx
  tests/components/user/LoginBox.spec.tsx
  tests/components/user/SignUpBox.spec.tsx
Labels: Site

#244 Fix lint-staged config
  lint-staged.config.js
Labels: Site, Infrastructure

#241 Add deploy script
  .github/workflows/ci-cd.yml
  .github/workflows/delete-branch-caches.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-review-app.yml
  .github/workflows/destroy-review-app.yml
  prisma/schema.prisma
Labels: Infrastructure, Refactor

#247 Remove jest-dom
  package-lock.json
  package.json
Labels: Infrastructure, Maintenance

#256 Set up node in prod deployment workflow
  .github/workflows/deploy-prod.yml
Labels: Infrastructure

#254 Do not make a PR comment on main
  .github/workflows/deploy-review-app.yml
Labels: Infrastructure

#262 Adapt alias handling
  .github/workflows/deploy-review-app.yml
  .github/workflows/destroy-review-app.yml
Labels: Infrastructure

#263 Remove db commands from vercel-build
  package.json
Labels: Infrastructure

#267 Add build cache for nextjs to CI
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-review-app.yml
Labels: Infrastructure

#242 Feature/style email templates
  emails/passwordReset.tsx
  emails/registration.tsx
  src/api/mail/mail.service.ts
  src/api/mail/send-password-reset-mail-context.interface.ts
  src/components/user/SignUpBox.tsx
Labels: enhancement, Content, Design, Refactor

#248 Feature/new profile page
  src/app/challenges/[challengeSlug]/page.tsx
  src/app/challenges/page.tsx
  src/components/Footer.tsx
  src/components/challenge/Preview.tsx
  src/components/challengePage/Card.tsx
  src/components/challengePage/ChallengeHeader.tsx
  src/components/challengePage/ChallengeList.tsx
  src/components/challengePage/ChallengeSignUpPrompt.tsx
  src/components/common/flashMessage/FlashMessage.tsx
  src/components/common/flashMessage/messages/EmailConfirmationFailedMessage.tsx
  src/components/evaluation/CollapsableSection.tsx
  src/components/evaluation/EvaluationHeader.tsx
  src/components/homepage/SignUpSection.tsx
  src/components/modal/Modal.tsx
  src/components/user/ChallengeStatus.tsx
  src/graphql/queries/challengesWithStatusForUser.graphql
  src/pages/profile/[userId].tsx
  tests/components/challengePage/ChallengeList.spec.tsx
  tests/components/common/flashMessage/messages/EmailConfirmationFailedMessage.spec.tsx
  tests/components/user/ChallengeStatus.spec.tsx
  tests/pages/profile/[userId].spec.tsx
Labels: Site, Design, Refactor

#268 Rename email
  src/api/user/models/user.model.ts
  src/components/common/flashMessage/messages/EmailConfirmationSuccessfulMessage.tsx
  src/components/user/LoginForm.tsx
  src/components/user/RequestPasswordResetBox.tsx
  src/components/user/RequestPasswordResetForm.tsx
  src/components/user/SignUpForm.tsx
  src/pages/press-kit.tsx
  src/pages/privacy-policy.tsx
  tests/api/unit/authentication/authentication.controller.spec.ts
  tests/api/unit/authentication/authentication.service.spec.ts
  tests/api/unit/authentication/graphql/resolvers/autentication.resolver.spec.ts
  tests/api/unit/mail/mail.service.spec.ts
  tests/api/unit/user/user.resolver.spec.ts
  tests/api/unit/user/user.service.spec.ts
  tests/components/common/flashMessage/messages/EmailConfirmationFailedMessage.spec.tsx
  tests/components/common/flashMessage/messages/EmailConfirmationSuccessfulMessage.spec.tsx
  tests/components/user/LoginForm.spec.tsx
  tests/components/user/RequestPasswordResetForm.spec.tsx
  tests/components/user/SignUpForm.spec.tsx
Labels: Site, API, Refactor

#243 Convert landingpage to AppRouter (server components)
  src/app/page.tsx
  src/components/common/flashMessage/FlashMessageContext.tsx
  src/components/homepage/CTASection.tsx
  src/components/homepage/HeroSection.tsx
  src/components/homepage/USPItem.tsx
  src/components/homepage/USPSection.tsx
  src/components/homepage/UseAnimationsContext.tsx
  src/pages/index.tsx
  tests/app/ClientProviders.spec.tsx
  tests/app/layout.spec.tsx
  tests/components/Navigation.spec.tsx
  tests/components/common/flashMessage/FlashMessageContext.spec.tsx
  tests/components/common/flashMessage/FlashMessagePortalRoot.spec.tsx
  tests/components/homepage/USPItem.spec.tsx
Labels: Site, Refactor

#269 Split up tasks in cleanup workflow
  .github/workflows/destroy-review-app.yml
Labels: Infrastructure
